### ISSUE TITLE
Plugin prevents IntelliJ from opening

### ISSUE THREAD

**Issue by solonovamax** [Vineflower/vineflower-intellij#23] opened 2024-08-13 04:36 UTC
Enabling the plugin in versions 2024.2 or 2024.1.6 causes IntelliJ to not open what so ever. Unsure if this is an issue with some configuration on my end, however I know for sure this is caused by the vineflower plugin.
This causes IntelliJ to remain stuck on the splash screen indefinitely.

I believe it has something to do with the "automatically downloads the latest vineflower updates on IDE startup" feature.

**Comment by Earthcomputer** [comment] 2024-08-14 07:19
Likely a duplicate of #21

**Closed by Earthcomputer** 2024-08-14 07:19 UTC

**Comment by solonovamax** [comment] 2024-08-14 07:20
This only started occurring really recently and had never happened before this

**Comment by solonovamax** [comment] 2024-08-15 17:57
Alright, epic.

I'm going to copy some of the contents of this conversation into that other issue, just for the sake of tracking, then.
